# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_unknown.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributeUnknown(object):
    def setupUi(self, AttributeUnknown):
        AttributeUnknown.setObjectName("AttributeUnknown")
        AttributeUnknown.resize(750, 40)
        AttributeUnknown.setMinimumSize(QtCore.QSize(575, 40))
        AttributeUnknown.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(AttributeUnknown)
        self.horizontalLayout_3.setContentsMargins(15, 2, 15, 2)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.num_attrib = QtWidgets.QLabel(AttributeUnknown)
        self.num_attrib.setMinimumSize(QtCore.QSize(50, 26))
        self.num_attrib.setMaximumSize(QtCore.QSize(50, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.num_attrib.setFont(font)
        self.num_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.num_attrib.setObjectName("num_attrib")
        self.horizontalLayout_3.addWidget(self.num_attrib)
        self.name_attrib = QtWidgets.QLabel(AttributeUnknown)
        self.name_attrib.setMinimumSize(QtCore.QSize(240, 26))
        self.name_attrib.setMaximumSize(QtCore.QSize(240, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_attrib.setFont(font)
        self.name_attrib.setObjectName("name_attrib")
        self.horizontalLayout_3.addWidget(self.name_attrib)
        self.icon_folder_2 = QtWidgets.QPushButton(AttributeUnknown)
        self.icon_folder_2.setEnabled(False)
        self.icon_folder_2.setMinimumSize(QtCore.QSize(40, 26))
        self.icon_folder_2.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.icon_folder_2.setFont(font)
        self.icon_folder_2.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/warning.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.icon_folder_2.setIcon(icon)
        self.icon_folder_2.setIconSize(QtCore.QSize(18, 18))
        self.icon_folder_2.setFlat(True)
        self.icon_folder_2.setObjectName("icon_folder_2")
        self.horizontalLayout_3.addWidget(self.icon_folder_2)
        self.name_layer = QtWidgets.QHBoxLayout()
        self.name_layer.setSpacing(0)
        self.name_layer.setObjectName("name_layer")
        self.value_attrib = QtWidgets.QLineEdit(AttributeUnknown)
        self.value_attrib.setEnabled(False)
        self.value_attrib.setMinimumSize(QtCore.QSize(100, 26))
        self.value_attrib.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.value_attrib.setFont(font)
        self.value_attrib.setStyleSheet("QLineEdit{padding-left: 5px; border: 1px solid #8f8f91; border-radius:5px; }")
        self.value_attrib.setObjectName("value_attrib")
        self.name_layer.addWidget(self.value_attrib)
        self.horizontalLayout_3.addLayout(self.name_layer)

        self.retranslateUi(AttributeUnknown)
        QtCore.QMetaObject.connectSlotsByName(AttributeUnknown)

    def retranslateUi(self, AttributeUnknown):
        _translate = QtCore.QCoreApplication.translate
        self.icon_folder_2.setToolTip(_translate("AttributeUnknown", "Attention, Numéro d\'attribut Inconnu !"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttributeUnknown = QtWidgets.QWidget()
    ui = Ui_AttributeUnknown()
    ui.setupUi(AttributeUnknown)
    AttributeUnknown.show()
    sys.exit(app.exec_())
