# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_catalog_recent.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatalogRecent(object):
    def setupUi(self, CatalogRecent):
        CatalogRecent.setObjectName("CatalogRecent")
        CatalogRecent.resize(350, 500)
        CatalogRecent.setStyleSheet("QWidget#CatalogRecent {background:#FFFFFF}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CatalogRecent)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(CatalogRecent)
        self.widget.setStyleSheet("QWidget#widget{border: 1px solid #8f8f91; border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-width: 0px;}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.folder_layer = QtWidgets.QHBoxLayout()
        self.folder_layer.setObjectName("folder_layer")
        self.etc_bt = QtWidgets.QPushButton(self.widget)
        self.etc_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.etc_bt.setFont(font)
        self.etc_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.etc_bt.setText("ETC")
        self.etc_bt.setCheckable(True)
        self.etc_bt.setChecked(True)
        self.etc_bt.setObjectName("etc_bt")
        self.folder_layer.addWidget(self.etc_bt)
        self.std_bt = QtWidgets.QPushButton(self.widget)
        self.std_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.std_bt.setFont(font)
        self.std_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.std_bt.setText("STD")
        self.std_bt.setCheckable(True)
        self.std_bt.setChecked(True)
        self.std_bt.setObjectName("std_bt")
        self.folder_layer.addWidget(self.std_bt)
        self.demo_bt = QtWidgets.QPushButton(self.widget)
        self.demo_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.demo_bt.setFont(font)
        self.demo_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.demo_bt.setText("Démo")
        self.demo_bt.setCheckable(True)
        self.demo_bt.setChecked(True)
        self.demo_bt.setObjectName("demo_bt")
        self.folder_layer.addWidget(self.demo_bt)
        self.other_bt = QtWidgets.QPushButton(self.widget)
        self.other_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.other_bt.setFont(font)
        self.other_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.other_bt.setCheckable(True)
        self.other_bt.setChecked(True)
        self.other_bt.setObjectName("other_bt")
        self.folder_layer.addWidget(self.other_bt)
        self.verticalLayout.addLayout(self.folder_layer)
        self.year_layer = QtWidgets.QHBoxLayout()
        self.year_layer.setObjectName("year_layer")
        self.a2022_bt = QtWidgets.QPushButton(self.widget)
        self.a2022_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.a2022_bt.setFont(font)
        self.a2022_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.a2022_bt.setText("2022")
        self.a2022_bt.setCheckable(True)
        self.a2022_bt.setChecked(True)
        self.a2022_bt.setObjectName("a2022_bt")
        self.year_layer.addWidget(self.a2022_bt)
        self.a2023_bt = QtWidgets.QPushButton(self.widget)
        self.a2023_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.a2023_bt.setFont(font)
        self.a2023_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.a2023_bt.setText("2023")
        self.a2023_bt.setCheckable(True)
        self.a2023_bt.setChecked(True)
        self.a2023_bt.setObjectName("a2023_bt")
        self.year_layer.addWidget(self.a2023_bt)
        self.a2024_bt = QtWidgets.QPushButton(self.widget)
        self.a2024_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.a2024_bt.setFont(font)
        self.a2024_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.a2024_bt.setText("2024")
        self.a2024_bt.setCheckable(True)
        self.a2024_bt.setChecked(True)
        self.a2024_bt.setObjectName("a2024_bt")
        self.year_layer.addWidget(self.a2024_bt)
        self.a2025_bt = QtWidgets.QPushButton(self.widget)
        self.a2025_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.a2025_bt.setFont(font)
        self.a2025_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.a2025_bt.setText("2025")
        self.a2025_bt.setCheckable(True)
        self.a2025_bt.setChecked(True)
        self.a2025_bt.setObjectName("a2025_bt")
        self.year_layer.addWidget(self.a2025_bt)
        self.a2026_bt = QtWidgets.QPushButton(self.widget)
        self.a2026_bt.setMinimumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.a2026_bt.setFont(font)
        self.a2026_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px;  }\n"
"QPushButton:checked{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }\n"
"QPushButton:hover{border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D8D8D8, stop:1 #FFFFFF); }")
        self.a2026_bt.setText("2026")
        self.a2026_bt.setCheckable(True)
        self.a2026_bt.setChecked(True)
        self.a2026_bt.setObjectName("a2026_bt")
        self.year_layer.addWidget(self.a2026_bt)
        self.verticalLayout.addLayout(self.year_layer)
        self.verticalLayout_2.addWidget(self.widget)
        self.hierarchy_recent = QtWidgets.QTreeView(CatalogRecent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hierarchy_recent.setFont(font)
        self.hierarchy_recent.setStyleSheet("border: 1px solid #8f8f91")
        self.hierarchy_recent.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.hierarchy_recent.setAlternatingRowColors(True)
        self.hierarchy_recent.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.hierarchy_recent.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.hierarchy_recent.setIconSize(QtCore.QSize(20, 20))
        self.hierarchy_recent.setObjectName("hierarchy_recent")
        self.hierarchy_recent.header().setVisible(False)
        self.hierarchy_recent.header().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.hierarchy_recent)

        self.retranslateUi(CatalogRecent)
        QtCore.QMetaObject.connectSlotsByName(CatalogRecent)
        CatalogRecent.setTabOrder(self.etc_bt, self.std_bt)
        CatalogRecent.setTabOrder(self.std_bt, self.demo_bt)
        CatalogRecent.setTabOrder(self.demo_bt, self.other_bt)
        CatalogRecent.setTabOrder(self.other_bt, self.a2022_bt)
        CatalogRecent.setTabOrder(self.a2022_bt, self.a2023_bt)
        CatalogRecent.setTabOrder(self.a2023_bt, self.a2024_bt)
        CatalogRecent.setTabOrder(self.a2024_bt, self.a2025_bt)
        CatalogRecent.setTabOrder(self.a2025_bt, self.a2026_bt)
        CatalogRecent.setTabOrder(self.a2026_bt, self.hierarchy_recent)

    def retranslateUi(self, CatalogRecent):
        _translate = QtCore.QCoreApplication.translate
        self.std_bt.setToolTip(_translate("CatalogRecent", "Supprimer la recherche"))
        self.other_bt.setText(_translate("CatalogRecent", "Autre"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CatalogRecent = QtWidgets.QWidget()
    ui = Ui_CatalogRecent()
    ui.setupUi(CatalogRecent)
    CatalogRecent.show()
    sys.exit(app.exec_())
