# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_ktlg_light.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KtlgLight(object):
    def setupUi(self, KtlgLight):
        KtlgLight.setObjectName("KtlgLight")
        KtlgLight.setWindowModality(QtCore.Qt.ApplicationModal)
        KtlgLight.resize(330, 138)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/asc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KtlgLight.setWindowIcon(icon)
        KtlgLight.setStyleSheet("QWidget#KtlgLight{background:#FFFFFF}")
        self.verticalLayout = QtWidgets.QVBoxLayout(KtlgLight)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_title = QtWidgets.QLabel(KtlgLight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_title.sizePolicy().hasHeightForWidth())
        self.info_title.setSizePolicy(sizePolicy)
        self.info_title.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.info_title.setFont(font)
        self.info_title.setStyleSheet("QLabel{border:1px solid #B2B2B2; border-right: 0px; padding-left: 5px; padding-right: 5px; background: #BAD0E7; border-radius:5px; }")
        self.info_title.setAlignment(QtCore.Qt.AlignCenter)
        self.info_title.setObjectName("info_title")
        self.verticalLayout.addWidget(self.info_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.current_title = QtWidgets.QLabel(KtlgLight)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.current_title.setFont(font)
        self.current_title.setObjectName("current_title")
        self.horizontalLayout.addWidget(self.current_title)
        self.current_bt = QtWidgets.QPushButton(KtlgLight)
        self.current_bt.setMinimumSize(QtCore.QSize(50, 24))
        self.current_bt.setMaximumSize(QtCore.QSize(50, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.current_bt.setFont(font)
        self.current_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.current_bt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/catalog.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.current_bt.setIcon(icon1)
        self.current_bt.setIconSize(QtCore.QSize(20, 20))
        self.current_bt.setObjectName("current_bt")
        self.horizontalLayout.addWidget(self.current_bt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.default_title = QtWidgets.QLabel(KtlgLight)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.default_title.setFont(font)
        self.default_title.setObjectName("default_title")
        self.horizontalLayout_2.addWidget(self.default_title)
        self.default_bt = QtWidgets.QPushButton(KtlgLight)
        self.default_bt.setMinimumSize(QtCore.QSize(50, 24))
        self.default_bt.setMaximumSize(QtCore.QSize(50, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.default_bt.setFont(font)
        self.default_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.default_bt.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/reset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.default_bt.setIcon(icon2)
        self.default_bt.setIconSize(QtCore.QSize(20, 20))
        self.default_bt.setObjectName("default_bt")
        self.horizontalLayout_2.addWidget(self.default_bt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.favorite_bt = QtWidgets.QPushButton(KtlgLight)
        self.favorite_bt.setMinimumSize(QtCore.QSize(30, 24))
        self.favorite_bt.setMaximumSize(QtCore.QSize(30, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.favorite_bt.setFont(font)
        self.favorite_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/favorite_open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.favorite_bt.setIcon(icon3)
        self.favorite_bt.setIconSize(QtCore.QSize(16, 16))
        self.favorite_bt.setObjectName("favorite_bt")
        self.horizontalLayout_3.addWidget(self.favorite_bt)
        self.option_bt = QtWidgets.QPushButton(KtlgLight)
        self.option_bt.setMinimumSize(QtCore.QSize(100, 24))
        self.option_bt.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.option_bt.setFont(font)
        self.option_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; padding-left: 5px; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.option_bt.setObjectName("option_bt")
        self.horizontalLayout_3.addWidget(self.option_bt)
        self.quit_bt = QtWidgets.QPushButton(KtlgLight)
        self.quit_bt.setMinimumSize(QtCore.QSize(100, 24))
        self.quit_bt.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.quit_bt.setFont(font)
        self.quit_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; padding-left: 5px; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.quit_bt.setShortcut("Ctrl+F4")
        self.quit_bt.setObjectName("quit_bt")
        self.horizontalLayout_3.addWidget(self.quit_bt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(KtlgLight)
        QtCore.QMetaObject.connectSlotsByName(KtlgLight)

    def retranslateUi(self, KtlgLight):
        _translate = QtCore.QCoreApplication.translate
        self.info_title.setText(_translate("KtlgLight", "Configuration rapide"))
        self.current_title.setText(_translate("KtlgLight", "Définir ce catalogue"))
        self.default_title.setText(_translate("KtlgLight", "Mettre les paramètres par défaut"))
        self.favorite_bt.setToolTip(_translate("KtlgLight", "Importer favoris"))
        self.option_bt.setText(_translate("KtlgLight", "Plus d\'options"))
        self.quit_bt.setText(_translate("KtlgLight", "Quitter"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KtlgLight = QtWidgets.QWidget()
    ui = Ui_KtlgLight()
    ui.setupUi(KtlgLight)
    KtlgLight.show()
    sys.exit(app.exec_())
